- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name: Deploy Docker image to k8s
    command: kubectl expose deployment health --type=LoadBalancer --port=8082 --target-port=8082

