- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name: create a deployment
    command: kubectl create deployment health --type=LoadBalancer --port=80 --target-port=80
 
  

