- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name: Deploy Docker image to Kubernetes
    command: kubectl expose deployment healthcare-deployment --type=LoadBalancer --port=80 --target-port=80

